All:
	g++ -O3 val_test01_solved.cpp -o val_test01_solved
	g++ -O3 val_test02_solved.cpp -o val_test02_solved
	g++ -fopenmp -O3 MMult1.cpp -o MMult1
	g++ -fopenmp omp_bug2_solved.c -o omp_bug2_solved
	g++ -fopenmp omp_bug3_solved.c -o omp_bug3_solved
	g++ -fopenmp omp_bug4_solved.c -o omp_bug4_solved
	g++ -fopenmp omp_bug5_solved.c -o omp_bug5_solved
	g++ -fopenmp omp_bug6_solved.c -o omp_bug6_solved
	g++ -fopenmp gs2D-omp.cpp -o gs2D-omp
	g++ -fopenmp jacobi2D-omp.cpp -o jacobi2D-omp






